# Generated by Django 4.2.2 on 2023-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=20)),
                ('about_discription', models.CharField(max_length=290)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
