# Generated by Django 4.2.2 on 2023-06-22 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_discription',
            field=models.TextField(max_length=290),
        ),
    ]
